<!DOCTYPE about_page [
    <!ELEMENT about_page (main_section)>
    <!ELEMENT main_section (company_info)>
    <!ELEMENT company_info (history, mission, vision)>
    <!ELEMENT history (#PCDATA)>
    <!ELEMENT mission (#PCDATA)>
    <!ELEMENT vision (#PCDATA)>
]>

<?xml-stylesheet type="text/css" href="xmlstyle.css"?>
<about_page>
  <main_section>
    <company_info>
      <history>Bryan's Cafe history information here</history>
      <mission>Bryan's Cafe mission information here</mission>
      <vision>Bryan's Cafe vision information here</vision>
    </company_info>
  </main_section>
</about_page>
