<!DOCTYPE privacy_policy_page [
    <!ELEMENT privacy_policy_page (main_section)>
    <!ELEMENT main_section (privacy_info)>
    <!ELEMENT privacy_info (collection, use, protection)>
    <!ELEMENT collection (#PCDATA)>
    <!ELEMENT use (#PCDATA)>
    <!ELEMENT protection (#PCDATA)>
]>

<?xml-stylesheet type="text/css" href="xmlstyle.css"?>

<privacy_policy_page>
    <main_section>
        <privacy_info>
            <collection>Detailed information about how the café collects personal information goes here.</collection>
            <use>Detailed information about how the café uses personal information goes here.</use>
            <protection>Detailed information about how the café protects personal information goes here.</protection>
        </privacy_info>
    </main_section>
</privacy_policy_page>
